"""Markdown output formatter for the final analysis report."""

from __future__ import annotations

import os
from datetime import datetime, timezone


def format_report(
    source_path: str,
    merged_content: str,
    cv_summary: str,
    analysis_meta: dict,
) -> str:
    """Produce the final markdown report.

    Parameters
    ----------
    source_path : str
        Path to the original image file.
    merged_content : str
        Consolidated VLM analysis (output of merge_tile_results).
    cv_summary : str
        Summary of computer-vision augmentation findings.
    analysis_meta : dict
        Metadata about the analysis run (timings, tile count, model, etc.).
    """
    filename = os.path.basename(source_path)
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    header = (
        f"# Network Diagram Analysis: {filename}\n\n"
        f"Generated by net-sight on {now}\n\n"
    )

    meta_section = _format_meta(analysis_meta)
    cv_section = f"## COMPUTER VISION FINDINGS\n\n{cv_summary}\n\n" if cv_summary else ""

    return header + meta_section + cv_section + merged_content + "\n"


def _format_meta(meta: dict) -> str:
    """Format analysis metadata as a markdown table."""
    if not meta:
        return ""

    lines = ["## ANALYSIS METADATA\n"]
    lines.append("| Parameter | Value |")
    lines.append("|---|---|")
    for k, v in meta.items():
        lines.append(f"| {k} | {v} |")
    lines.append("\n")
    return "\n".join(lines)


def format_cv_summary(
    lines_count: int,
    texts_count: int,
    shapes_count: int,
    color_clusters: int,
) -> str:
    """Produce a human-readable summary of CV augmentation results."""
    parts = []
    parts.append(f"- **Lines detected**: {lines_count} segments")
    parts.append(f"- **Text elements**: {texts_count} labels extracted via OCR")
    parts.append(f"- **Shapes detected**: {shapes_count} (rectangles, circles, polygons)")
    parts.append(f"- **Color categories**: {color_clusters} distinct line color groups")
    return "\n".join(parts)
